language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
jobs:
include:         # this works for Linux but is ignored on macOS or Windows
  - name: "Python 3.7.4 on macOS"
    os: osx
    osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
    language: shell       # 'language: python' is an error on Travis CI macOS
  - name: "Python 3.8.0 on Windows"
    os: windows           # Windows 10.0.17134 N/A Build 17134
    language: shell       # 'language: python' is an error on Travis CI Windows
    before_install:
      - choco install python --version 3.8.0
      - python -m pip install --upgrade pip
      - python setup.py install
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install: 
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install -r requirements.txt
  - pip3 install -i https://test.pypi.org/simple/ riscv-assembler==9.9.18 #giving test version
  - pip3 install riscv-assembler
script: pytest

#TASKS
#[] fix requirements.txt